"""empty message

Revision ID: b1d3ca593492
Revises: 
Create Date: 2023-01-30 16:36:06.076615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1d3ca593492'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gpa', sa.Float(), nullable=True),
    sa.Column('code', sa.Integer(), nullable=False),
    sa.Column('ownerId', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('group_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('individual_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('publish', sa.Boolean(), nullable=True),
    sa.Column('deadline', sa.Boolean(), nullable=True),
    sa.Column('authorize', sa.Boolean(), nullable=True),
    sa.Column('studentCount', sa.Boolean(), nullable=True),
    sa.Column('sId', sa.Integer(), nullable=True),
    sa.Column('gpa', sa.Float(), nullable=True),
    sa.Column('member', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['member'], ['group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('proposal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('desc', sa.String(length=2064), nullable=False),
    sa.Column('published', sa.Boolean(), nullable=True),
    sa.Column('fId', sa.Integer(), nullable=True),
    sa.Column('gId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fId'], ['user.id'], ),
    sa.ForeignKeyConstraint(['gId'], ['group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('proposal', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_proposal_desc'), ['desc'], unique=True)
        batch_op.create_index(batch_op.f('ix_proposal_title'), ['title'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proposal', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_proposal_title'))
        batch_op.drop_index(batch_op.f('ix_proposal_desc'))

    op.drop_table('proposal')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    op.drop_table('individual_report')
    op.drop_table('group_report')
    op.drop_table('group')
    # ### end Alembic commands ###
